Repository hmcts/ecm-consumer, pull requests merged in 2021-11, with the labels that each got.

#381 cve suppressed
  config/owasp/suppressions.xml
Labels: ns:ethos, prd:ethos, rel:ethos-ecm-consumer-pr-381

#383 ecm-common version upgrade
  build.gradle
Labels: ns:ethos, prd:ethos, rel:ethos-ecm-consumer-pr-383

#379 the next release branch
  build.gradle
  config/owasp/suppressions.xml
  src/main/resources/application.properties
Labels: ns:ethos, prd:ethos, rel:ethos-ecm-consumer-pr-379

#386 ecm-common version upgrade
  build.gradle
Labels: ns:ethos, prd:ethos, rel:ethos-ecm-consumer-pr-386

#384 R.5.0.19 candidate
  build.gradle
Labels: ns:ethos, prd:ethos, rel:ethos-ecm-consumer-pr-384

#387 update common version
  build.gradle
Labels: ns:ethos, prd:ethos, rel:ethos-ecm-consumer-pr-387

#388 Release 5.0.20
  build.gradle
Labels: ns:ethos, prd:ethos, rel:ethos-ecm-consumer-pr-388
