Repository hmcts/ecm-consumer, pull requests merged in 2021-07, with the labels that each got.

#307 ECM-31: Batch update judgement fails
  build.gradle
Labels: ns:ethos, prd:ethos, rel:ethos-ecm-consumer-pr-307

#308 ECM-176 fixed.
  src/main/java/uk/gov/hmcts/reform/ethos/ecm/consumer/service/SingleTransferService.java
Labels: ns:ethos, prd:ethos, rel:ethos-ecm-consumer-pr-308

#310 ECM-31: Batch update judgement fails if no jurisdictions present in j…
  build.gradle
Labels: ns:ethos, prd:ethos, rel:ethos-ecm-consumer-pr-310

#313 ecm common version updated
  build.gradle
Labels: ns:ethos, prd:ethos, rel:ethos-ecm-consumer-pr-313

#315 Ecm common version updated
  build.gradle
Labels: ns:ethos, prd:ethos, rel:ethos-ecm-consumer-pr-315

#298 Merging R5.0.11 to Master branch
  build.gradle
  config/owasp/suppressions.xml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  src/main/java/uk/gov/hmcts/reform/ethos/ecm/consumer/service/SingleTransferService.java
  src/test/functional/java/uk/gov/hmcts/ethos/ecm/consumer/functional/HealthCheckTest.java
Labels: ns:ethos, prd:ethos, rel:ethos-ecm-consumer-pr-298

#342 updated build
  build.gradle
Labels: ns:ethos, prd:ethos, rel:ethos-ecm-consumer-pr-342

#323 R5.0.12
  build.gradle
  src/main/java/uk/gov/hmcts/reform/ethos/ecm/consumer/service/SingleUpdateService.java
Labels: ns:ethos, prd:ethos, rel:ethos-ecm-consumer-pr-323

#345 Add CVE suppressions
  config/owasp/suppressions.xml
Labels: ns:ethos, prd:ethos, rel:ethos-ecm-consumer-pr-345

#349 CVE suppressed
  config/owasp/suppressions.xml
Labels: ns:ethos, prd:ethos, rel:ethos-ecm-consumer-pr-349

#350 helm chart version updated
  charts/ethos-ecm-consumer/Chart.yaml
  config/owasp/suppressions.xml
Labels: ns:ethos, prd:ethos, rel:ethos-ecm-consumer-pr-350

#352 email updated
  charts/ethos-ecm-consumer/Chart.yaml
Labels: ns:ethos, prd:ethos, rel:ethos-ecm-consumer-pr-352
