Repository hmcts/ecm-consumer, pull requests merged in 2021-12, with the labels that each got.

#390 Update Jenkinsfile_nightly
  Jenkinsfile_nightly
Labels: ns:ethos, prd:ethos, rel:ethos-ecm-consumer-pr-390

#389 Update log4J version
  build.gradle
Labels: ns:ethos, prd:ethos, rel:ethos-ecm-consumer-pr-389

#392 Update log4J version
  build.gradle
Labels: ns:ethos, prd:ethos, rel:ethos-ecm-consumer-pr-392

#391 R5.0.21
  build.gradle
Labels: ns:ethos, prd:ethos, rel:ethos-ecm-consumer-pr-391

#393 Re-enable Fortify
  Jenkinsfile_nightly
  config/fortify-client.properties
Labels: ns:ethos, prd:ethos, rel:ethos-ecm-consumer-pr-393

#395 ECM-220 Rename caseData.caseType to ecmCaseType
  build.gradle
  src/main/java/uk/gov/hmcts/reform/ethos/ecm/consumer/service/SingleCreationService.java
Labels: ns:ethos, prd:ethos, rel:ethos-ecm-consumer-pr-395
