Repository hmcts/ecm-consumer, pull requests merged in 2021-06, with the labels that each got.

#266 R5.0.9
  build.gradle
  src/main/java/uk/gov/hmcts/reform/ethos/ecm/consumer/service/SingleCreationService.java
Labels: ns:ethos, prd:ethos, rel:ethos-ecm-consumer-pr-266

#285 added suppress cve
  config/owasp/suppressions.xml
Labels: ns:ethos, prd:ethos, rel:ethos-ecm-consumer-pr-285

#305 ECM-8: Fix CVEs
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:ethos, prd:ethos, rel:ethos-ecm-consumer-pr-305
