Repository hmcts/ecm-consumer, pull requests merged in 2021-09, with the labels that each got.

#369 Fortify
  Jenkinsfile_nightly
  build.gradle
  config/fortify-client.properties
Labels: ns:ethos, prd:ethos, rel:ethos-ecm-consumer-pr-369

#370 Ecm221 fortify
  Jenkinsfile_nightly
  build.gradle
  config/fortify-client.properties
Labels: ns:ethos, prd:ethos, rel:ethos-ecm-consumer-pr-370

#372 multiple reference link set
  build.gradle
  src/main/java/uk/gov/hmcts/reform/ethos/ecm/consumer/service/SingleUpdateService.java
  src/main/java/uk/gov/hmcts/reform/ethos/ecm/consumer/tasks/CreateUpdatesBusReceiverTask.java
  src/main/java/uk/gov/hmcts/reform/ethos/ecm/consumer/tasks/UpdateCaseBusReceiverTask.java
Labels: ns:ethos, prd:ethos, rel:ethos-ecm-consumer-pr-372

#373 UpdateCaseBusReceiverTask modified
  build.gradle
  config/owasp/suppressions.xml
  src/main/java/uk/gov/hmcts/reform/ethos/ecm/consumer/service/SingleUpdateService.java
  src/main/java/uk/gov/hmcts/reform/ethos/ecm/consumer/tasks/UpdateCaseBusReceiverTask.java
Labels: ns:ethos, prd:ethos, rel:ethos-ecm-consumer-pr-373

#375 cve suppressed
  config/owasp/suppressions.xml
Labels: ns:ethos, prd:ethos, rel:ethos-ecm-consumer-pr-375
