Repository hmcts/ecm-consumer, pull requests merged in 2022-03, with the labels that each got.

#410 R5.0.25
  build.gradle
Labels: ns:ethos, prd:ethos, rel:ethos-ecm-consumer-pr-410

#441 Bump base Java helm chart to 3.7.2
  charts/ethos-ecm-consumer/Chart.yaml
Labels: ns:ethos, prd:ethos, rel:ethos-ecm-consumer-pr-441

#442 Bump Spring Boot
  build.gradle
  charts/ethos-ecm-consumer/Chart.yaml
  charts/ethos-ecm-consumer/values.preview.template.yaml
  charts/ethos-ecm-consumer/values.yaml
  src/main/java/uk/gov/hmcts/reform/ethos/ecm/consumer/config/SwaggerConfiguration.java
  src/main/java/uk/gov/hmcts/reform/ethos/ecm/consumer/service/AccessTokenService.java
  src/main/resources/application.properties
  src/main/resources/bootstrap.yaml
Labels: ns:ethos, prd:ethos, rel:ethos-ecm-consumer-pr-442

#445 Bump base java chart to 3.7.3
  charts/ethos-ecm-consumer/Chart.yaml
Labels: ns:ethos, prd:ethos, rel:ethos-ecm-consumer-pr-445

#443 R5.0.26
  build.gradle
  charts/ethos-ecm-consumer/Chart.yaml
  charts/ethos-ecm-consumer/values.preview.template.yaml
  charts/ethos-ecm-consumer/values.yaml
  src/main/java/uk/gov/hmcts/reform/ethos/ecm/consumer/config/SwaggerConfiguration.java
  src/main/java/uk/gov/hmcts/reform/ethos/ecm/consumer/service/AccessTokenService.java
  src/main/resources/application.properties
  src/main/resources/bootstrap.yaml
Labels: ns:ethos, prd:ethos, rel:ethos-ecm-consumer-pr-443

#446 ECM Release 5.0.26
  build.gradle
Labels: ns:ethos, prd:ethos, rel:ethos-ecm-consumer-pr-446

#452 Bump versions
  build.gradle
Labels: ns:ethos, prd:ethos, rel:ethos-ecm-consumer-pr-452

#454 new cve
  config/owasp/suppressions.xml
Labels: ns:ethos, prd:ethos, rel:ethos-ecm-consumer-pr-454

#457 Release 5.0.27
  build.gradle
Labels: ns:ethos, prd:ethos, rel:ethos-ecm-consumer-pr-457
