Repository hmcts/ecm-consumer, pull requests merged in 2022-09, with the labels that each got.

#602 snakeyaml CVE fix added
  build.gradle
Labels: ns:ethos, prd:ethos, rel:ethos-ecm-consumer-pr-602

#616 batik dependency CVEs fix
  build.gradle
Labels: ns:ethos, prd:ethos, rel:ethos-ecm-consumer-pr-616

#588 ECM-900: remove email notification
  build.gradle
  charts/ethos-ecm-consumer/Chart.yaml
  charts/ethos-ecm-consumer/values.preview.template.yaml
  charts/ethos-ecm-consumer/values.yaml
  src/main/java/uk/gov/hmcts/reform/ethos/ecm/consumer/config/EmailClient.java
  src/main/java/uk/gov/hmcts/reform/ethos/ecm/consumer/helpers/Constants.java
  src/main/java/uk/gov/hmcts/reform/ethos/ecm/consumer/service/EmailService.java
  src/main/java/uk/gov/hmcts/reform/ethos/ecm/consumer/service/UpdateManagementService.java
  src/main/resources/application.properties
  src/test/java/uk/gov/hmcts/reform/ethos/ecm/consumer/service/EmailServiceTest.java
  src/test/java/uk/gov/hmcts/reform/ethos/ecm/consumer/service/UpdateManagementServiceTest.java
Labels: ns:ethos, prd:ethos, rel:ethos-ecm-consumer-pr-588
