Repository hmcts/ecm-consumer, pull requests merged in 2022-08, with the labels that each got.

#583 Fix CVEs
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:ethos, prd:ethos, rel:ethos-ecm-consumer-pr-583

#585 Fix postgresql CVE
  build.gradle
Labels: ns:ethos, prd:ethos, rel:ethos-ecm-consumer-pr-585

#597 Add backstage configuration file
  catalog-info.yaml
Labels: ns:ethos, prd:ethos, rel:ethos-ecm-consumer-pr-597
