Repository hmcts/ecm-consumer, pull requests merged in 2022-05, with the labels that each got.

#480 R5.0.29
  build.gradle
  config/owasp/suppressions.xml
  src/main/java/uk/gov/hmcts/reform/ethos/ecm/consumer/domain/repository/MultipleCounterRepository.java
  src/main/java/uk/gov/hmcts/reform/ethos/ecm/consumer/service/SingleUpdateService.java
  src/main/java/uk/gov/hmcts/reform/ethos/ecm/consumer/tasks/CreateUpdatesBusReceiverTask.java
  src/main/resources/application-dev.properties
  src/main/resources/application.properties
  src/main/resources/sqlscripts/fn_persistentQ_InsertFirstMultipleCountVal_v1.0.sql
  src/main/resources/sqlscripts/tbls_PersistentQ_multiplecounter_v1.0.sql
  src/test/java/uk/gov/hmcts/reform/ethos/ecm/consumer/service/SingleUpdateServiceTest.java
  src/test/java/uk/gov/hmcts/reform/ethos/ecm/consumer/service/UpdateManagementServiceTest.java
  src/test/java/uk/gov/hmcts/reform/ethos/ecm/consumer/tasks/CreateUpdatesBusReceiverTaskTest.java
  src/test/java/uk/gov/hmcts/reform/ethos/ecm/consumer/tasks/UpdateCaseBusReceiverTaskTest.java
Labels: ns:ethos, prd:ethos, rel:ethos-ecm-consumer-pr-480

#507 revert changes from ECM-690 until new function is added on prod db
  src/main/java/uk/gov/hmcts/reform/ethos/ecm/consumer/tasks/CreateUpdatesBusReceiverTask.java
Labels: ns:ethos, prd:ethos, rel:ethos-ecm-consumer-pr-507

#513 bump versions
  build.gradle
Labels: ns:ethos, prd:ethos, rel:ethos-ecm-consumer-pr-513

#512 uncommented code
  src/main/java/uk/gov/hmcts/reform/ethos/ecm/consumer/tasks/CreateUpdatesBusReceiverTask.java
Labels: ns:ethos, prd:ethos, rel:ethos-ecm-consumer-pr-512

#522 bump versions
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:ethos, prd:ethos, rel:ethos-ecm-consumer-pr-522

#534 R5.0.30
  config/owasp/suppressions.xml
  renovate.json
Labels: ns:ethos, prd:ethos, rel:ethos-ecm-consumer-pr-534

#536 CVEs
  config/owasp/suppressions.xml
Labels: ns:ethos, prd:ethos, rel:ethos-ecm-consumer-pr-536
