Repository hmcts/ecm-consumer, pull requests merged in 2022-02, with the labels that each got.

#404 Update ECM-Common version
  build.gradle
Labels: ns:ethos, prd:ethos, rel:ethos-ecm-consumer-pr-404

#401 R5.0.23
  build.gradle
  src/main/java/uk/gov/hmcts/reform/ethos/ecm/consumer/config/HttpClientConfiguration.java
  src/main/resources/application.properties
Labels: ns:ethos, prd:ethos, rel:ethos-ecm-consumer-pr-401

#406 Update build.gradle
  build.gradle
Labels: ns:ethos, prd:ethos, rel:ethos-ecm-consumer-pr-406

#407 CVEs
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:ethos, prd:ethos, rel:ethos-ecm-consumer-pr-407

#408 Update Chart.yaml
  charts/ethos-ecm-consumer/Chart.yaml
Labels: ns:ethos, prd:ethos, rel:ethos-ecm-consumer-pr-408

#405 R5.0.24
  build.gradle
  charts/ethos-ecm-consumer/Chart.yaml
  config/owasp/suppressions.xml
Labels: ns:ethos, prd:ethos, rel:ethos-ecm-consumer-pr-405

#409 Bump base java helm chart to 3.7.1
  charts/ethos-ecm-consumer/Chart.yaml
Labels: ns:ethos, prd:ethos, rel:ethos-ecm-consumer-pr-409

#432 ECM-614
  build.gradle
Labels: ns:ethos, prd:ethos, rel:ethos-ecm-consumer-pr-432

#436 pmd removed
  build.gradle
Labels: ns:ethos, prd:ethos, rel:ethos-ecm-consumer-pr-436
