Repository hmcts/ecm-consumer, pull requests merged in 2022-04, with the labels that each got.

#466 ECM-691
  build.gradle
Labels: ns:ethos, prd:ethos, rel:ethos-ecm-consumer-pr-466

#473 CVE-2022-22965
  build.gradle
Labels: ns:ethos, prd:ethos, rel:ethos-ecm-consumer-pr-473

#474 ECM-677 Bump the version in chart.yaml
  charts/ethos-ecm-consumer/Chart.yaml
Labels: ns:ethos, prd:ethos, rel:ethos-ecm-consumer-pr-474

#479 Update org.springframework.boot
  build.gradle
Labels: ns:ethos, prd:ethos, rel:ethos-ecm-consumer-pr-479

#481 R5.0.28
  build.gradle
Labels: ns:ethos, prd:ethos, rel:ethos-ecm-consumer-pr-481

#483 Update suppressions.xml
  config/owasp/suppressions.xml
Labels: ns:ethos, prd:ethos, rel:ethos-ecm-consumer-pr-483

#485 CVE suppressions
  config/owasp/suppressions.xml
Labels: ns:ethos, prd:ethos, rel:ethos-ecm-consumer-pr-485

#489 CVE-2022-23708
  build.gradle
Labels: ns:ethos, prd:ethos, rel:ethos-ecm-consumer-pr-489

#491 Release 5.0.27
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:ethos, prd:ethos, rel:ethos-ecm-consumer-pr-491

#497 cves
  config/owasp/suppressions.xml
Labels: ns:ethos, prd:ethos, rel:ethos-ecm-consumer-pr-497

#500 fix
  src/main/resources/sqlscripts/fn_persistentQ_InsertFirstMultipleCountVal_v1.0.sql
  src/main/resources/sqlscripts/tbls_PersistentQ_multiplecounter_v1.0.sql
Labels: ns:ethos, prd:ethos, rel:ethos-ecm-consumer-pr-500
