Repository hmcts/ecm-consumer, pull requests merged in 2024-02, with the labels that each got.

#687 Postgres
  build.gradle
  charts/ethos-ecm-consumer/Chart.yaml
  charts/ethos-ecm-consumer/values.yaml
  infrastructure/flexi_db.tf
  infrastructure/main.tf
  infrastructure/variables.tf
Labels: ns:ethos, prd:ethos, add-or-update, rel:ethos-ecm-consumer-pr-687

#770 Update variables.tf
  infrastructure/main.tf
  infrastructure/variables.tf
Labels: ns:ethos, prd:ethos, add-or-update, rel:ethos-ecm-consumer-pr-770

#773 Dtspo 16806 test automation
  infrastructure/flexi_db.tf
  infrastructure/ithc.tfvars
Labels: ns:ethos, prd:ethos, add-or-update, rel:ethos-ecm-consumer-pr-773

#774 Revert "Dtspo 16806 test automation"
  infrastructure/flexi_db.tf
  infrastructure/ithc.tfvars
Labels: ns:ethos, prd:ethos, rel:ethos-ecm-consumer-pr-774

#771 Update flexi_db.tf
  infrastructure/flexi_db.tf
Labels: ns:ethos, prd:ethos, destroy, rel:ethos-ecm-consumer-pr-771

#772 v15 switchover
  charts/ethos-ecm-consumer/Chart.yaml
  charts/ethos-ecm-consumer/values.yaml
Labels: ns:ethos, prd:ethos, rel:ethos-ecm-consumer-pr-772
